import tkinter as tk
from Mapa import CAMINO, LIANA, TUNEL, MURO
from Interfaz import Interfaz

# Mapa de prueba fijo de 10x10
mapa_prueba = [
    [CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO],
    [CAMINO, MURO,   LIANA,  CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO],
    [CAMINO, CAMINO, CAMINO, CAMINO, TUNEL,  CAMINO, CAMINO, CAMINO, CAMINO, CAMINO],
    [CAMINO, CAMINO, MURO,   CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO],
    [CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO],
    [CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO],
    [CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO],
    [CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO],
    [CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO],
    [CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO, CAMINO],
]

def iniciar():
    root = tk.Tk()
    root.title("Prueba de mapa 10x10 y movimiento")
    Interfaz(root, mapa_prueba)
    root.mainloop()

if __name__ == "__main__":
    iniciar()